### PR TITLE
Remove previous v49 fix + explanation

### PR DESCRIPTION
**Pull request by PrimoDev23**
Hey,
you might have missed the comment in my previous MR, but I told you to add the v50 Landmine method.

I just did not want to update, but since v50 is officially out now I had some time to test the v50 binaries and implement the version myself.

This will fix v50, while keeping compatibility with v49

### CODE REVIEW

**Comment by PrimoDev23** [comment]
@Theronguard Please don't merge this!!! There are other methods failing. I will need to implement more from the old binaries

**Comment by PrimoDev23** [comment]
@Theronguard Honestly, there are too many methods to copy from the old v49 binaries. Since v50 is out already, it will not be worth the effort. I would suggest applying this MR (which just reverts my changes, since it only covered Landmines) and upload the attached zip to thunderstore. It is compiled using the v49 binaries and uses version "1.1.21".

[Theronguard-Emergency_Dice-1.1.21.zip](https://github.com/Theronguard/Emergency-Dice/files/14969715/Theronguard-Emergency_Dice-1.1.21.zip)

Then upload another version "1.1.22" compiled with the v50 binaries and add a hint to the mod description, that "1.1.21" is the last version supporting v49.
This way you can satisfy everyones needs, without breaking anyones experience.

**Comment by Theronguard** [comment]
Thanks a lot! I won't be home until friday, so I'll probably analyze and merge this on saturday unless I find some time on the trip.

**Comment by Theronguard** [comment]
I will add a note in the next update that **1.1.16** was the last version supporting v49. Thank you for your effort.

**Pull request closed without merging**
